site_name: adaptiveFDA
theme: material
plugins:
  - search
  - redirects:
      redirect_maps:
        index.md: index.html
nav:
  - Home: index.md
  - FDA research at CREST: crest_research.md
  - Introduction to FDA:
    - Paradigm shift: intro_paradigm.md
    - Fields of application: intro_fields_app.md
    - Use cases: intro_usecases.md
  - R package:
    - Introduction: pkg_intro.md
  - Glossary: glossary.md
