site_name: adaptiveFDA
theme: material
plugins:
  - search
  - redirects:
      redirect_maps:
        'index.md': 'en/index.md'
        'fr/index.md': 'fr/index.md'
nav:
  - Home: 
      - English: en/index.md
      - Français: fr/index.md
  - FDA research at CREST:
      - English: en/crest_research.md
      - Français: fr/crest_research.md
  - Introduction to FDA:
    - Paradigm shift:
      - English: en/intro_paradigm.md
      - Français: fr/intro_paradigm.md
    - Fields of application:
      - English: en/intro_fields_app.md
      - Français: fr/intro_fields_app.md
    - Use cases:
      - English: en/intro_usecases.md
      - Français: fr/intro_usecases.md
  - R package:
    - Introduction:
      - English: en/pkg_intro.md
      - Français: fr/pkg_intro.md
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Français
      link: /fr/
      lang: fr
