site_name: adaptiveFDA
theme: material
plugins:
  - search
  - redirects:
      redirect_maps:
        index.md: index.html
nav:
  - Adaptive Functional Data Analysis: index.md
  - FDA research at CREST: crest_research.md
  - Introduction to FDA:
    - Paradigm shift: intro_paradigm.md
