site_name: adaptiveFDA
theme: material
plugins:
  - search
  - redirects:
      redirect_maps:
        'index.md': 'en/index.md'
nav:
  - Home: index.md
  - FDA research at CREST: crest_research.md
  - Introduction to FDA:
    - Paradigm shift: intro_paradigm.md
    - Fields of application: intro_fields_app.md
    - Use cases: intro_usecases.md
  - R package:
    - Introduction: pkg_intro.md
extra:
  alternate:
    - name: English
      link: /quick-start/en/ 
      lang: en
    - name: Français
      link: /quick-start/fr/
      lang: fr
